source/objects/Order_Fulfillment_BO__b.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>SF Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipName>ProcessingOrder</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SourceSystem__c</fullName>
        <label>SourceSystem</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TransactionID__c</fullName>
        <label>TransactionID</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TransactionTimestamp__c</fullName>
        <label>TransactionTimestamp</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TransactionType__c</fullName>
        <label>TransactionType</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Order Fulfillment BO</label>
    <pluralLabel>Order Fulfillment BOs</pluralLabel>
</CustomObject>

source/classes/HistoricalOrderFulfillmentsCtrlr.cls
public class HistoricalOrderFulfillmentsCtrlr {
    @AuraEnabled
    public static List<Order_Fulfillment_BO__b> getHistoricalFulfillmentsForOrder(String orderID) {
        List<Order_Fulfillment_BO__b> hist = [SELECT SourceSystem__c, TransactionID__c, TransactionType__c, TransactionTimestamp__c, Description__c
                                           FROM Order_Fulfillment_BO__b where Order__c=:orderID Order By  Order__c ASC, TransactionType__c ASC, TransactionTimestamp__c DESC  LIMIT 50];
              
        return hist;
    }
}