source/objects/Order_Fulfillment_Event__e.object
<CustomObject>
    <fields>
        <fullName>SF_Order_ID__c</fullName>
        <label>SF Order ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_System__c</fullName>
        <label>Source System</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_ID__c</fullName>
        <label>Transaction ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Timestamp__c</fullName>
        <label>Transaction Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Order Fulfillment Event</label>
    <pluralLabel>Order Fulfillment Events</pluralLabel>
</CustomObject>

source/classes/TestTrigger.cls
@isTest
public class TestTrigger {
    @isTest static void testValidEvent() {
        
        // Create a test event instance
        Order_Fulfillment_Event__e myEvt = new Order_Fulfillment_Event__e(SF_Order_ID__c='123', 
                                             Source_System__c='source', 
                                             Transaction_ID__c='id',
                                             Transaction_Type__c='type'
                                              ,Transaction_Timestamp__c=Datetime.now()
                                                                         );
        
        
      
        
        Test.startTest();
        
        // Publish test event
        Database.SaveResult sr = EventBus.publish(myEvt);
            
        Test.stopTest();
                
        // Perform validations here
        
        // Verify SaveResult value
        System.assertEquals(true, sr.isSuccess());
        

    }
    
 
}